name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "? ? * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #- name: Install
        #run: npm ci
      - name: Update gist
        uses: Saika-Z/waka-box@master
        #run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: https://gist.github.com/Saika-Z/af515579e9ab638d1de80d38175d2881
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
