name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: Saika-Z/waka-box@master
      - name: Update gist
        uses: Saika-Z/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: af515579e9ab638d1de80d38175d2881
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
