name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: Saika-Z/waka-box@master
      - name: Update gist
        uses: Saika-Z/waka-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: https://gist.github.com/Saika-Z/af515579e9ab638d1de80d38175d2881
          WAKATIME_API_KEY: 1e69b805-f7ff-4799-bd44-d37d15c2d078
